name: Notifications on push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: thatcoder
        DISCORD_AVATAR: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTjxQgor36gXF1grBxcWqpjnqJP5TuM5C9VPDJdJahpvI8MQ6xy
      uses: that-coder/kafka-example@master
      with:
        args: 'A new commit has been pushed to Ilshidur/action-discord.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: that-coder/kafka-example@master
